
package LoginMenu;
import Functions.dbConnection;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yali_il
 */
public class resetPassword extends javax.swing.JFrame {

    /**
     * Creates new form resetRegistrationPage
     */
    public resetPassword() {
        initComponents();
        Toolkit toolkit  = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
    }
    ResultSet rs = null;
    PreparedStatement pst,st = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revealAsterisk = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        vcfield = new javax.swing.JTextField();
        gBTLI = new javax.swing.JButton();
        emptyvcfield = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emptynPass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emptycPass = new javax.swing.JLabel();
        vc = new javax.swing.JLabel();
        vc1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emptyefield = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Npassword = new javax.swing.JPasswordField();
        Cpassword = new javax.swing.JPasswordField();
        revealAsterisk2 = new javax.swing.JToggleButton();

        revealAsterisk.setBackground(new java.awt.Color(255, 255, 255));
        revealAsterisk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageIcon/visibility-2.png"))); // NOI18N
        revealAsterisk.setBorder(null);
        revealAsterisk.setBorderPainted(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(183, 76, 76));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Reset password");

        reset.setText("Reset user");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        vcfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vcfieldKeyReleased(evt);
            }
        });

        gBTLI.setText("Go Back To Log In");
        gBTLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBTLIActionPerformed(evt);
            }
        });

        emptyvcfield.setForeground(new java.awt.Color(255, 0, 51));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("New password:");

        emptynPass.setForeground(new java.awt.Color(255, 0, 51));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm password:");

        emptycPass.setForeground(new java.awt.Color(255, 0, 51));

        vc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vc.setText("Verification code:");

        vc1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vc1.setText("Email:");

        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
        });

        emptyefield.setForeground(new java.awt.Color(255, 0, 51));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("@gmail.com");

        revealAsterisk2.setBackground(new java.awt.Color(255, 255, 255));
        revealAsterisk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageIcon/visibility-2.png"))); // NOI18N
        revealAsterisk2.setBorder(null);
        revealAsterisk2.setBorderPainted(false);
        revealAsterisk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revealAsterisk2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emptycPass, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(Cpassword)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(gBTLI)
                                .addGap(18, 18, 18)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vcfield, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(emptynPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emptyvcfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Npassword)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(vc1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emptyefield, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(revealAsterisk2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vc1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addComponent(emptyefield, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vcfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(emptyvcfield, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Npassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(emptynPass, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(revealAsterisk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(emptycPass, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gBTLI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gBTLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBTLIActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_gBTLIActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
            
                if(emailField.getText().trim().isEmpty()&&vcfield.getText().trim().isEmpty()&&Npassword.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                    emptyvcfield.setText("The verification code field is empty");
                    emptynPass.setText("The new password field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(emailField.getText().trim().isEmpty()&&vcfield.getText().trim().isEmpty()&&Npassword.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                    emptyvcfield.setText("The verification code field is empty");
                    emptynPass.setText("The new password field is empty");
                }else if(emailField.getText().trim().isEmpty()&&vcfield.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                    emptyvcfield.setText("The verification code field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(emailField.getText().trim().isEmpty()&&Npassword.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                    emptynPass.setText("The new password field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(vcfield.getText().trim().isEmpty()&&Npassword.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                    emptynPass.setText("The new password field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(vcfield.getText().trim().isEmpty()&&emailField.getText().trim().isEmpty()){
                    emptyvcfield.setText("The verification code field is empty");
                    emptyefield.setText("The email field is empty");
                }else if(Npassword.getText().trim().isEmpty()&&emailField.getText().trim().isEmpty()){
                    emptynPass.setText("The new password field is empty");
                    emptyefield.setText("The email field is empty");
                }else if(Cpassword.getText().trim().isEmpty()&&emailField.getText().trim().isEmpty()){
                    emptycPass.setText("The confirm password field is empty");
                    emptyefield.setText("The email field is empty");
                }else if(vcfield.getText().trim().isEmpty()&&Npassword.getText().trim().isEmpty()){
                    emptyvcfield.setText("The verification code field is empty");
                    emptynPass.setText("The new password field is empty");
                }else if(vcfield.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptyvcfield.setText("The verification code field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(Npassword.getText().trim().isEmpty()&&Cpassword.getText().trim().isEmpty()){
                    emptynPass.setText("The new password field is empty");
                    emptycPass.setText("The confirm password field is empty");
                }else if(emailField.getText().trim().isEmpty()){
                    emptyefield.setText("The email field is empty");
                }else if(vcfield.getText().trim().isEmpty()){
                    emptyvcfield.setText("The verification code field is empty");
                }else if(Cpassword.getText().trim().isEmpty()){
                    emptycPass.setText("The confirm password field is empty");
                }else if(Npassword.getText().trim().isEmpty()){
                    emptynPass.setText("The new password field is empty");
                }else{
                if (Npassword.getText().equals(Cpassword.getText())){
                    try{
                        String sql2 = "SELECT * FROM InventoryManagementSystem.signlog where verifycode=?";
                        pst = dbConnection.getConnection().prepareStatement(sql2);
                        pst.setString(1, vcfield.getText()); 
                        ResultSet rs2 = pst.executeQuery();
                        
                        if(rs2.next()){
                            String query = "UPDATE signlog set password= ? WHERE email =?";
                            pst = dbConnection.getConnection().prepareStatement(query);
                            pst.setString(1,Cpassword.getText());
                            pst.setString(2,emailField.getText()+"@gmail.com");
                            pst.executeUpdate();
                            
                            String sql = "SELECT * FROM InventoryManagementSystem.signlog where email=? and password=?";
                            st = dbConnection.getConnection().prepareStatement(sql);
                            st.setString(1, emailField.getText()+"@gmail.com");
                            st.setString(2, Cpassword.getText());
                            rs = st.executeQuery();
                            
                            if(rs.next()){
                                JOptionPane.showMessageDialog(null,"Password successfully changed");
                                Login l = new Login();
                                l.setVisible(true);
                                setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(null,"Email is not registered");
                                emailField.setText("");
                                
                            }
                        } else{
                            JOptionPane.showMessageDialog(null,"Verification do not matched");
                            vcfield.setText("");
                            
                        }

                    } catch(Exception ex){
                        JOptionPane.showMessageDialog(null,ex);
                    }
                } else{
                    JOptionPane.showMessageDialog(null,"Password do not match");
                    vcfield.setText("");
                    Npassword.setText("");
                    Cpassword.setText("");
                }
                }
            
            
    }//GEN-LAST:event_resetActionPerformed

    private void vcfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcfieldKeyReleased
        // TODO add your handling code here:
        emptyvcfield.setText("");
    }//GEN-LAST:event_vcfieldKeyReleased

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldKeyReleased

    private void revealAsterisk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revealAsterisk2ActionPerformed
        // TODO add your handling code here:
        if(revealAsterisk2.isSelected()){
            // Show the password in plain text
            Npassword.setEchoChar((char)0);
            Cpassword.setEchoChar((char)0);
        }else {
            // Hide the password behind asterisks
            Npassword.setEchoChar('*');
            Cpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_revealAsterisk2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpassword;
    private javax.swing.JPasswordField Npassword;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emptycPass;
    private javax.swing.JLabel emptyefield;
    private javax.swing.JLabel emptynPass;
    private javax.swing.JLabel emptyvcfield;
    private javax.swing.JButton gBTLI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton reset;
    private javax.swing.JToggleButton revealAsterisk;
    private javax.swing.JToggleButton revealAsterisk2;
    private javax.swing.JLabel vc;
    private javax.swing.JLabel vc1;
    private javax.swing.JTextField vcfield;
    // End of variables declaration//GEN-END:variables
}
