package InventoryMenu;
import Functions.Download;
import Functions.dbConnection;
import LoginMenu.Login;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.*;
import java.net.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.apache.poi.xssf.usermodel.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yali_il
 */
public class manageInventoryImport extends javax.swing.JFrame {

    /**
     * Creates new form manageInventory
     */
    public manageInventoryImport() {
        initComponents();
        Toolkit toolkit  = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
        SelectItem();
        getCategory();
        getUnit();
        tableResizer();
        tableResizer2();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        inventory = new javax.swing.JButton();
        categories = new javax.swing.JButton();
        suppliers = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        unit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        iname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cprice = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        importbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        categorycb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        itemid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        unitcb = new javax.swing.JComboBox<>();
        Refresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ImportTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clearbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(183, 76, 76));
        jLabel1.setText("Inventory Management System");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(183, 76, 76));
        jButton1.setText("Get User Guide");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(183, 76, 76));

        inventory.setBackground(new java.awt.Color(255, 255, 255));
        inventory.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inventory.setForeground(new java.awt.Color(183, 76, 76));
        inventory.setText("Inventory");
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        categories.setBackground(new java.awt.Color(183, 76, 76));
        categories.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        categories.setForeground(new java.awt.Color(255, 255, 255));
        categories.setText("Category");
        categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesActionPerformed(evt);
            }
        });

        suppliers.setBackground(new java.awt.Color(183, 76, 76));
        suppliers.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        suppliers.setForeground(new java.awt.Color(255, 255, 255));
        suppliers.setText("Supplier");
        suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(183, 76, 76));
        logout.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        unit.setBackground(new java.awt.Color(183, 76, 76));
        unit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        unit.setForeground(new java.awt.Color(255, 255, 255));
        unit.setText("Unit");
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventory, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
            .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(suppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(183, 76, 76));
        jLabel2.setText("Manage Inventory");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(183, 76, 76));
        jLabel4.setText("Selling price");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(183, 76, 76));
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(183, 76, 76));
        jLabel6.setText("Category");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(183, 76, 76));
        jLabel7.setText("Cost price");

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtnMouseClicked(evt);
            }
        });

        importbtn.setBackground(new java.awt.Color(255, 255, 255));
        importbtn.setText("Import");
        importbtn.setToolTipText("<html> For more information on how to import<br>Please click the 'Get User Guide'</html>");
        importbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importbtnActionPerformed(evt);
            }
        });

        InventoryTable.setAutoCreateRowSorter(true);
        InventoryTable.setBackground(new java.awt.Color(255, 255, 255));
        InventoryTable.setForeground(new java.awt.Color(0, 0, 0));
        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Category", "Quantity", "Unit", "Cost price", "Total cost", "Selling price"
            }
        ));
        InventoryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InventoryTable.setFocusable(false);
        InventoryTable.setRowHeight(24);
        InventoryTable.setSelectionBackground(new java.awt.Color(183, 76, 76));
        InventoryTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        InventoryTable.setShowGrid(true);
        InventoryTable.getTableHeader().setResizingAllowed(false);
        InventoryTable.getTableHeader().setReorderingAllowed(false);
        InventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InventoryTable);

        categorycb.setBackground(new java.awt.Color(255, 255, 255));
        categorycb.setForeground(new java.awt.Color(255, 255, 255));
        categorycb.setToolTipText("<html> To have more options for the category<br>Please click the 'Category' button</html>");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(183, 76, 76));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(183, 76, 76));
        jLabel9.setText("Item Name");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(183, 76, 76));
        jLabel10.setText("Item ID");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(183, 76, 76));
        jLabel11.setText("Unit");

        unitcb.setBackground(new java.awt.Color(255, 255, 255));
        unitcb.setForeground(new java.awt.Color(255, 255, 255));
        unitcb.setToolTipText("<html> To have more options for the unit<br>Please click the 'Unit' button</html>");

        Refresh.setBackground(new java.awt.Color(255, 255, 255));
        Refresh.setText("Refresh");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        ImportTable.setAutoCreateRowSorter(true);
        ImportTable.setBackground(new java.awt.Color(255, 255, 255));
        ImportTable.setForeground(new java.awt.Color(0, 0, 0));
        ImportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Category", "Quantity", "Unit", "Cost price", "Total cost", "Selling price"
            }
        ));
        ImportTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ImportTable.setFocusable(false);
        ImportTable.setRowHeight(24);
        ImportTable.setSelectionBackground(new java.awt.Color(183, 76, 76));
        ImportTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        ImportTable.setShowGrid(true);
        ImportTable.getTableHeader().setResizingAllowed(false);
        ImportTable.getTableHeader().setReorderingAllowed(false);
        ImportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ImportTable);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(183, 76, 76));
        jLabel12.setText("Import Table");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(183, 76, 76));
        jLabel13.setText("Inventory Table");

        clearbtn1.setBackground(new java.awt.Color(255, 255, 255));
        clearbtn1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        clearbtn1.setForeground(new java.awt.Color(183, 76, 76));
        clearbtn1.setText("Exit Import");
        clearbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtn1MouseClicked(evt);
            }
        });
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });

        itemid.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(iname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(unitcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorycb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cprice, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(sprice))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(263, 263, 263)
                        .addComponent(clearbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clearbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(categorycb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel7)
                                            .addGap(48, 48, 48))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(cprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(sprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(unitcb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
        } 
        
    }//GEN-LAST:event_logoutActionPerformed

    private void categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesActionPerformed
        // TODO add your handling code here:
        manageCategory ms = new manageCategory();
        ms.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_categoriesActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
        manageInventory mi = new manageInventory();
        mi.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_inventoryActionPerformed

    private void suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersActionPerformed
        // TODO add your handling code here:
        manageSupplier mc = new manageSupplier();
        mc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_suppliersActionPerformed
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
    public void SelectItem(){
        try{
            st = dbConnection.getConnection().createStatement();
            rs = st.executeQuery("SELECT * FROM InventoryManagementSystem.inventory");
            InventoryTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e){
                e.printStackTrace();
        }
    }
    public void getCategory(){
        try{
            st = dbConnection.getConnection().createStatement();
            String query = "SELECT * FROM InventoryManagementSystem.category";
            rs = st.executeQuery(query);
            while(rs.next()){
                String myCat = rs.getString("Category Name");
                categorycb.addItem(myCat);
            }
        } catch(Exception e){
                e.printStackTrace();
        }
    }
    public void getUnit(){
        try{
            st = dbConnection.getConnection().createStatement();
            String query = "SELECT * FROM InventoryManagementSystem.unit";
            rs = st.executeQuery(query);
            while(rs.next()){
                String unit = rs.getString("Unit name");
                unitcb.addItem(unit);
            }
        } catch(Exception e){
                e.printStackTrace();
        }
    }
    
    public void tableResizer(){
        TableColumnModel colmod = InventoryTable.getColumnModel();
        TableColumn TC_ItemID = colmod.getColumn(0);
        TC_ItemID.setPreferredWidth(20);
        TableColumn TC_ItemName = colmod.getColumn(1);
        TC_ItemName.setPreferredWidth(200);
        TableColumn TC_Category = colmod.getColumn(2);
        TC_Category.setPreferredWidth(50);
        TableColumn TC_ItemQuantity = colmod.getColumn(3);
        TC_ItemQuantity.setPreferredWidth(20);
        TableColumn TC_ItemUnit = colmod.getColumn(4);
        TC_ItemUnit.setPreferredWidth(30);
        TableColumn TC_Cprice = colmod.getColumn(5);
        TC_Cprice.setPreferredWidth(30);
        TableColumn TC_totalCost = colmod.getColumn(6);
        TC_totalCost.setPreferredWidth(30);
        TableColumn TC_sellingPrice = colmod.getColumn(7);
        TC_sellingPrice.setPreferredWidth(30);
    }
    public void tableResizer2(){
        TableColumnModel colmod = ImportTable.getColumnModel();
        TableColumn TC_ItemID = colmod.getColumn(0);
        TC_ItemID.setPreferredWidth(20);
        TableColumn TC_ItemName = colmod.getColumn(1);
        TC_ItemName.setPreferredWidth(200);
        TableColumn TC_Category = colmod.getColumn(2);
        TC_Category.setPreferredWidth(50);
        TableColumn TC_ItemQuantity = colmod.getColumn(3);
        TC_ItemQuantity.setPreferredWidth(20);
        TableColumn TC_ItemUnit = colmod.getColumn(4);
        TC_ItemUnit.setPreferredWidth(30);
        TableColumn TC_Cprice = colmod.getColumn(5);
        TC_Cprice.setPreferredWidth(30);
        TableColumn TC_totalCost = colmod.getColumn(6);
        TC_totalCost.setPreferredWidth(30);
        TableColumn TC_sellingPrice = colmod.getColumn(7);
        TC_sellingPrice.setPreferredWidth(30);
    }
    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:       
        if (iname.getText().isEmpty()||quantity.getText().isEmpty()||cprice.getText().isEmpty()||sprice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try{
                String sql = "INSERT into InventoryManagementSystem.inventory VALUES(?,?,?,?,?,?,?,?)"; 
                String reset = "ALTER TABLE InventoryManagementSystem.inventory AUTO_INCREMENT = 1";
                PreparedStatement add  = dbConnection.getConnection().prepareStatement(sql);
                PreparedStatement r  = dbConnection.getConnection().prepareStatement(reset);
                
                Statement stmt = dbConnection.getConnection().createStatement();
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM inventory");

                // Get the count from the result set
                int count = 0;
                int num  =  0;
                if (rs.next()) {
                    count = rs.getInt(1);
                    num = count+1;
                }
                
                
                add.setString(1,String.valueOf(num));
                add.setString(2,iname.getText());
                add.setString(3,categorycb.getSelectedItem().toString());
                add.setFloat(4,Float.valueOf(quantity.getText()));
                add.setString(5,unitcb.getSelectedItem().toString());
                add.setFloat(6,Float.valueOf(cprice.getText()));
                float tquantity = Integer.valueOf(quantity.getText());
                float tcprice = Float.valueOf((cprice.getText()));
                add.setFloat(7,tquantity*tcprice);
                add.setFloat(8,Float.valueOf(sprice.getText()));
                r.executeUpdate();
                int row = add.executeUpdate(); 

                JOptionPane.showMessageDialog(this, "Item Added Successfully");
                SelectItem();
                tableResizer();
                itemid.setText("");
                iname.setText("");
                quantity.setText("");
                cprice.setText("");
                sprice.setText("");
                

                } catch(Exception e){
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_addbtnMouseClicked

    private void InventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)InventoryTable.getModel();
        int myindex = InventoryTable.getSelectedRow();
        itemid.setText(model.getValueAt(myindex, 0).toString());
        iname.setText(model.getValueAt(myindex, 1).toString());
        categorycb.setSelectedItem(model.getValueAt(myindex,2).toString());
        quantity.setText(model.getValueAt(myindex, 3).toString());
        unitcb.setSelectedItem(model.getValueAt(myindex,4).toString());
        cprice.setText(model.getValueAt(myindex, 5).toString());
        sprice.setText(model.getValueAt(myindex,7).toString()); 
        
        
    }//GEN-LAST:event_InventoryTableMouseClicked

    private void clearbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseClicked
         // TODO add your handling code here:
         itemid.setText("");
         iname.setText("");
         quantity.setText("");
         cprice.setText("");
         sprice.setText("");
         
    }//GEN-LAST:event_clearbtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "File is being downloaded\nPlease wait about 1 minute");
        Download d = new Download();
        d.pdfDownload();
        JOptionPane.showMessageDialog(this, "File is Downloaded\nPlease go check your Downloads to see the file");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void importbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ImportTable.getModel();
        File excelFile;
        
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportWorkbook = null;
        
        String home = System.getProperty("user.home");
              
        String defaultCurrentDirectoryPath = home+"/Downloads";
        JFileChooser excelFileChooserImport = new JFileChooser(defaultCurrentDirectoryPath);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("EXCEL FILES","xls","xlsx","xslm");
        excelFileChooserImport.setFileFilter(filter);
        
        int excelChooser = excelFileChooserImport.showOpenDialog(null);
        
        if(excelChooser == JFileChooser.APPROVE_OPTION){
            try {
                
                excelFile = excelFileChooserImport.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                
                excelImportWorkbook = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportWorkbook.getSheetAt(0);
                
                for (int row = 1; row <= excelSheet.getLastRowNum(); row++){
                    XSSFRow excelRow = excelSheet.getRow(row);
                    
                    XSSFCell excelName = excelRow.getCell(0);
                    model.addRow(new Object[] {"",excelName,"","","","","",""});
                }
                
                JOptionPane.showMessageDialog(null, "Data has been imported");
                tableResizer();
        
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }                   
        }
    }//GEN-LAST:event_importbtnActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
        manageUnit mu = new manageUnit();
        mu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_unitActionPerformed

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        int r = ImportTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)ImportTable.getModel();
        for (int j=0; j<r; j++){
            model.removeRow(0);
        }
        SelectItem();
        tableResizer();
        tableResizer2();
    }//GEN-LAST:event_RefreshActionPerformed

    private void ImportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ImportTable.getModel();
        int myindex = ImportTable.getSelectedRow();
        iname.setText(model.getValueAt(myindex, 1).toString());
    }//GEN-LAST:event_ImportTableMouseClicked

    private void clearbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbtn1MouseClicked

    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        // TODO add your handling code here:
        manageInventory mi = new manageInventory();
        mi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_clearbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageInventoryImport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ImportTable;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton categories;
    private javax.swing.JComboBox<String> categorycb;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JTextField cprice;
    private javax.swing.JButton importbtn;
    private javax.swing.JTextField iname;
    private javax.swing.JButton inventory;
    private javax.swing.JTextField itemid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sprice;
    private javax.swing.JButton suppliers;
    private javax.swing.JButton unit;
    private javax.swing.JComboBox<String> unitcb;
    // End of variables declaration//GEN-END:variables
}
